version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   UID: "1000"
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./src:/var/www