version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: "1000"
    ports:
      - "80:80"
    restart: unless-stopped

  # sut:
  #   image: alpine:3.13
  #   depends_on:
  #     - app
  #   command: /tmp/run_tests.sh
  #   volumes:
  #     - "./run_tests.sh:/tmp/run_tests.sh:ro"
